title: 星座演进说
description: 谢谢我喜欢你
author:
  name: 欸欸

defaults:
  - scope:
      path: 星座
      type: posts
    values:
      description: 在思考星座
  - scope:
      path: 摘录
    values:
      description: >
        摘录、存档；
        存档会整理格式，之后注解，在正文中引用。
  # Journals
  - scope:
      path: "星座/白羊/_posts/tweets"
      type: posts
    values:
      output: false
      permalink: journal/:year/:month/:day/:title
      category: journals

lang: zh-Hans #会在<html>加lang，和CSS搭配实现中文诗词排版（https://hmua.github.io/排版/2022/9/17/诗词风格排版）
timezone: Asia/Shanghai #修正ghpages服务器时区比国内晚导致不马上发布（https://hmua.github.io/建站/2022/9/25/在线编辑器使用问题）
#source: 星座 #在StackOverflow上看到的写法，测试后无效，可能缺什么条件

#
remote_theme: hmua/Customized-Minima
permalink: /:categories/:year/:i_month/:i_day/:title #网址，不在月日前加零，结尾什么都不加
#permalink: pretty

#对kramdown、GFM语法的选择，影响非常多而复杂，也没有人整理，只能自己边摸索边记录
#https://github.com/hmua/hmua.github.io/blob/main/建站/Jekyll/_posts/23-5-21-kramdown和GFM设置的影响.md
markdown: kramdown
#markdown: GFM

#模板（主题模板）中使用
show_excerpts: true #首页显示节选

titles_from_headings:
  #strip_title: true #这条什么作用忘了，好像是page标题会重复，现在只用post

minima:
  social_links:
    - { platform: devto,          user_url: "https://pages.github.com/versions" }
    - { platform: dribbble,       user_url: "https://jekyll.github.io/minima/" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    - { platform: github,         user_url: "https://github.com" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: linkedin,       user_url: "https://www.linkedin.com/in/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }
  #   - { platform: rss,            user_url: "https://jekyll.github.io/minima/feed.xml" }
  
prose: #用Prose.io时经常自动加published:false的frontmatter，通过此设置避免
  siteurl: "http://hmua.github.io"
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
