title: 星座演进说
description: 欸欸，在思考星座
author:
  name: 欸欸
lang: zh-Hans
timezone: Asia/Shanghai

# Markdown，正文排版
#markdown: kramdown
  
# Markdown之外，目录、首页、正文外格式
show_excerpts: true#首页显示节选
titles_from_headings:
  strip_title: true

#
remote_theme: hmua/Customized-Minima
permalink: /:categories/:year/:i_month/:i_day/:title #网址，不在月日前加零，结尾什么都不加

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  
prose:
  siteurl: "http://hmua.github.io"
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "published"
          value: "true"
          
  
