title: 星座演进说
description: 欸欸，在思考星座
lang: zh-Hans
timezone: Asia/Shanghai

# Markdown，正文排版
#markdown: kramdown
  
# Markdown之外，目录、首页、正文外格式
show_excerpts: true
titles_from_headings:
  strip_title: true
  
#
remote_theme: hmua/minima
permalink: pretty

export TZ: "Asia/Shanghai"
defaults:
  -
    scope:
      path: ""
      types: "posts"
    values:
      #timezone: Asia/Shanghai

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
