title: 星座演进说
description: 欸欸，在思考星座
lang: zh-Hans

# Markdown，正文排版
markdown: kramdown
kramdown:
  parser: gfm
  header_offset: 1
  
# Markdown之外，目录、首页、正文外格式
show_excerpts: true
titles_from_headings:
  strip_title: true
  
#
remote_theme: hmua/minima
permalink: pretty
